### ISSUE TITLE
CKEditor + Calendar issue in New Django Jet 

### ISSUE THREAD

**Issue by logicappsource** [jet-admin/jet-django#10]
First all amazing job I love the new UI !! Especialy in dark theme ...

But unfortunately migrating from the old Jet-admin to this. 

- CK-editor widget is not displaying 
- Functions like clickable calendar not functional either.. 

This makes an issue that migrating might be to long time 

I will wait excited for when new updates is available all the best! 

Jet view exception
Traceback (most recent call last):
  File "/Users/dev/PycharmProjects/MYNORDICROOM19/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/dev/PycharmProjects/MYNORDICROOM19/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: near "(": syntax error

**Comment by f1nality** [comment]
@logicappsource hello! what do you mean ck editor and calendar not working?

You can check the demo application here to see it works (ck editor and calendar on date fields)
https://app.jetadmin.io/demo?link=%2Fmodels%2Fcontrib;restaurantnewsitem%2F265

The error you've sent after is somthing different, please open a new issue for it

**Comment by logicappsource** [comment]
I followed the setup guide and installed through pip.
CKEDITOR did not work out of the box. 

is there any kind of requirements? (The field was just showing up as regular field)

I´m really keen to get the new dashboard implemented!!  

Thanks for respond @f1nality

**Comment by f1nality** [comment]
@logicappsource oh, i understood. by default all text fields are just char fields without ck editor and so on. jet supports customization with interface builder, read more about it here:
https://docs.jetadmin.io/manipulate/summary-view

in fact you need to go to record page containing text field, enable customize mode, select change view editing, click customize button over text field and select HTML mode option for your text field.
