### ISSUE TITLE
Question regarding Caching

### ISSUE THREAD

**Issue by Vadorequest** [jet-admin/jet-django#5]
I wonder how can we improve performances using a Cache system.

I'm not familiar with caching in Django, but everywhere I look it's all about views/templates, not about the DB data themselves.

What I'd like to do, is that Jet Django should query my cache first and then fallback on the DB.
I don't know how this is handled by the `jet_django` package, but I assume it uses the models to query the DB.

What should I configure, so that all read queries go through a cache before hitting the DB?

This may not be related to jet-django, but I'm not sure.

**Comment by f1nality** [comment]
It doesn't make sense for Jet Admin since you want to fetch actual data. Also backoffice application is not something used by millions of users, even big companies will have too few traffic for cache to be needed.
